services:
  server:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      - LARAVEL_DATABASE_HOST=database
      - LARAVEL_DATABASE_NAME=photo_manager
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=1234
      - LARAVEL_DATABASE_PORT_NUMBER=3306
    restart: always
    ports:
      - 8000:80

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=photo_manager
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database    
      PMA_PORT: 3306
    depends_on:
      - database

  chat:
    build: ./chat-server
    container_name: chat-server
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
