name: Deploy Laravel App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Laravel Docker image
        run: docker build -t yehiaarja/laravel-app ./backend

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push yehiaarja/laravel-app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull yehiaarja/laravel-app
            sudo docker compose up -f /backend/docker-compose.yml -d
